//update/create a prefernce(user, reacuring shift, score)
//create a reacuringshift(shift day, shift startHour, shiftEndHour, shift Jobtype)
//create a new user(username, password justicepoints)
//update a user information(userid, newusername, newpassword, newjusticepoints)
//create a constraint(start_time, end_time, user)
